name       : python-gphoto2
version    : 2.0.0
release    : 6
source     :
    - https://github.com/jim-easterbrook/python-gphoto2/archive/v2.0.0.tar.gz : b18f1f7acccc084464153161554801f7a305b73c832359fc208b9d9008125f35
license    : GPL-3.0-or-later
component  : programming.python
summary    : Python interface to libgphoto2
description: |
    python-gphoto2 is a comprehensive Python interface (or binding) to libgphoto2. It is built using SWIG to automatically generate the interface code. This gives direct access to nearly all the libgphoto2 functions, but sometimes in a rather un-Pythonic manner.
builddeps  :
    - pkgconfig(libgphoto2)
    - pkgconfig(python3)
    - swig
setup      : |
    python3 setup.py build_swig
    %python3_setup
install    : |
    %python3_install
