name       : python-gphoto2
version    : 2.2.3
release    : 11
source     :
    - https://github.com/jim-easterbrook/python-gphoto2/archive/v2.2.3.tar.gz : 546e6ed2e5393c5bde51d53882ad62bb93852ffdfcc1532337e1ed5b7a18690d
homepage   : https://github.com/jim-easterbrook/python-gphoto2
license    : GPL-3.0-or-later
component  : programming.python
summary    : Python interface to libgphoto2
description: |
    python-gphoto2 is a comprehensive Python interface (or binding) to libgphoto2. It is built using SWIG to automatically generate the interface code. This gives direct access to nearly all the libgphoto2 functions, but sometimes in a rather un-Pythonic manner.
builddeps  :
    - pkgconfig(libgphoto2)
    - pkgconfig(python3)
    - swig
setup      : |
    python3 setup.py build_swig
    %python3_setup
install    : |
    %python3_install
