name       : python-gphoto2
version    : 1.9.0
release    : 5
source     :
    - https://github.com/jim-easterbrook/python-gphoto2/archive/v1.9.0.tar.gz : 73a5a6d7d583ead8b9d8b28f7cce4e20345477caae9cd59606ffbc3f13631a10
license    : GPL-3.0-or-later
component  : programming.python
summary    : Python interface to libgphoto2
description: |
    python-gphoto2 is a comprehensive Python interface (or binding) to libgphoto2. It is built using SWIG to automatically generate the interface code. This gives direct access to nearly all the libgphoto2 functions, but sometimes in a rather un-Pythonic manner.
builddeps  :
    - pkgconfig(libgphoto2)
    - pkgconfig(python3)
    - swig
setup      : |
    python3 setup.py build_swig
    %python3_setup
install    : |
    %python3_install
