name       : python-gphoto2
version    : 2.3.2
release    : 12
source     :
    - https://github.com/jim-easterbrook/python-gphoto2/archive/v2.3.2.tar.gz : 4318187fbbf1eddbd4924cfed13a4e5ebbd43e043bd351fa741cb1cf9fb1e213
homepage   : https://github.com/jim-easterbrook/python-gphoto2
license    : GPL-3.0-or-later
component  : programming.python
summary    : Python interface to libgphoto2
description: |
    python-gphoto2 is a comprehensive Python interface (or binding) to libgphoto2. It is built using SWIG to automatically generate the interface code. This gives direct access to nearly all the libgphoto2 functions, but sometimes in a rather un-Pythonic manner.
builddeps  :
    - pkgconfig(libgphoto2)
    - pkgconfig(python3)
    - swig
build      : |
    python3 developer/build_swig.py system
    %python3_setup
install    : |
    %python3_install
