name       : python-gphoto2
version    : 1.8.2
release    : 4
source     :
    - https://github.com/jim-easterbrook/python-gphoto2/archive/v1.8.2.tar.gz : 92c16a1d926d30f6500a24861ff596e47508db69dc29bc6e065dcd65d0fde933
license    : GPL-3.0
component  : programming.python
summary    : Python interface to libgphoto2
description: |
    python-gphoto2 is a comprehensive Python interface (or binding)
    to libgphoto2. It is built using SWIG to automatically generate the
    interface code. This gives direct access to nearly all the libgphoto2
    functions, but sometimes in a rather un-Pythonic manner.
builddeps  :
    - pkgconfig(libgphoto2)
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - swig
setup      : |
    python setup.py build_swig
    python3 setup.py build_swig
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
